# Use the official PostgreSQL image from the Docker Hub
FROM postgres:14

# Set environment variables for PostgreSQL initialization
ENV POSTGRES_DB=mydatabase
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword

# Copy SQL initialization scripts into the container
COPY postgres-init/ /docker-entrypoint-initdb.d/

# Expose PostgreSQL port
EXPOSE 5432