openapi: 3.0.3
info:
  title: News and Content API
  description: API for managing news articles and content
  version: 1.0.0
paths:
  /news:
    get:
      summary: Get all news articles
      operationId: getAllNews
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/News'
    post:
      summary: Create a new news article
      operationId: createNews
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
  /news/{id}:
    get:
      summary: Get a news article by ID
      operationId: getNewsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
        '404':
          description: Not Found
    put:
      summary: Update a news article by ID
      operationId: updateNewsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewsInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/News'
        '404':
          description: Not Found
    delete:
      summary: Delete a news article by ID
      operationId: deleteNewsById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
  /content:
    get:
      summary: Get all content items
      operationId: getAllContent
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
    post:
      summary: Create a new content item
      operationId: createContent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
  /content/{id}:
    get:
      summary: Get a content item by ID
      operationId: getContentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '404':
          description: Not Found
    put:
      summary: Update a content item by ID
      operationId: updateContentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContentInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
        '404':
          description: Not Found
    delete:
      summary: Delete a content item by ID
      operationId: deleteContentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
components:
  schemas:
    News:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
    NewsInput:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
    Content:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        url:
          type: string
        type:
          type: string
    ContentInput:
      type: object
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          
