-- Drop tables if they exist
DROP TABLE IF EXISTS newstag;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS author;
CREATE TABLE author (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE news (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) UNIQUE NOT NULL,
    content TEXT NOT NULL,
    author_id BIGINT,
    created VARCHAR(255),
    modified VARCHAR(255),
    FOREIGN KEY (author_id) REFERENCES author(id)
);

CREATE TABLE comment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content TEXT NOT NULL,
    news_id BIGINT,
    created VARCHAR(255),
    modified VARCHAR(255),
    FOREIGN KEY (news_id) REFERENCES news(id)
);

CREATE TABLE tag (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE newstag (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    news_id BIGINT,
    tag_id BIGINT,
    FOREIGN KEY (news_id) REFERENCES news(id),
    FOREIGN KEY (tag_id) REFERENCES tag(id)
);

-- Reset auto-increment counters
ALTER TABLE author ALTER COLUMN id RESTART WITH (SELECT MAX(id) FROM author) + 1;
ALTER TABLE news ALTER COLUMN id RESTART WITH (SELECT MAX(id) FROM news) + 1;
ALTER TABLE comment ALTER COLUMN id RESTART WITH (SELECT MAX(id) FROM comment) + 1;
ALTER TABLE tag ALTER COLUMN id RESTART WITH (SELECT MAX(id) FROM tag) + 1;
ALTER TABLE newstag ALTER COLUMN id RESTART WITH (SELECT MAX(id) FROM newstag) + 1;