openapi: "3.0.3"
info:
  description: This is a simple API for news management
  version: 1.0.0
  title: News Service API
paths:
  /api/authors:
    get:
      tags:
        - AuthorService
      summary: List all authors
      operationId: getAuthors
      responses:
        '200':
          description: List of authors
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/AuthorModel'
    post:
      tags:
        - AuthorService
      summary: Create a new author
      operationId: createAuthor
      requestBody:
        description: Author object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorModel'
      responses:
        '201':
          description: Created author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorModel'
  /api/authors/{authorId}:
    get:
      tags:
        - AuthorService
      summary: Get author by ID
      operationId: getAuthorById
      parameters:
        - name: "authorId"
          in: "path"
          description: "ID of the author to retrieve"
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Retrieved author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorModel'
    put:
      tags:
        - AuthorService
      summary: Update an author by ID
      operationId: updateAuthor
      parameters:
        - name: "authorId"
          in: "path"
          description: "ID of the author to update"
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Author object with updated information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorModel'
      responses:
        '200':
          description: Updated author
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorModel'
    delete:
      tags:
        - AuthorService
      summary: Delete an author by ID
      operationId: deleteAuthor
      parameters:
        - name: "authorId"
          in: "path"
          description: "ID of the author to delete"
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Author deleted successfully
  /api/authors/search:
    get:
      tags:
        - AuthorService
      summary: Search authors by part of their name
      operationId: searchAuthorsByName
      parameters:
        - name: name
          in: query
          description: Part of the name of the authors to search for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of authors matching the search criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuthorModel'
components:
  schemas:
    AuthorModel:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
