openapi: "3.0.3"
info:
  description: This is a simple API for news management
  version: 1.0.0
  title: News Service API
paths:
  /api/authors:
    get:
      tags:
        - AuthorService
      summary: List all authors
      operationId: getAuthors
      responses:
        '200':
          description: List of authors
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/AuthorModel'

  /api/news:
    get:
      tags:
        - NewsService
      summary: List all news articles
      operationId: getAllNews
      responses:
        '200':
          description: List of news articles
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/NewsModel'

  /api/news/{newsId}:
    get:
      tags:
        - NewsService
      summary: Get news article by ID
      operationId: getNewsById
      parameters:
        - name: "newsId"
          in: "path"
          description: "ID of the news article to retrieve"
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Retrieved news article
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsModel'

components:
  schemas:
    AuthorModel:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    NewsModel:
      type: object
      required:
        - id
        - title
        - newsContent
        - author
        - created
        - modified
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        newsContent:
          type: string
        author:
          $ref: '#/components/schemas/AuthorModel'
        created:
          type: string
        modified:
          type: string
